### ISSUE TITLE
Configuration:Methadone

### ISSUE THREAD

**Issue by oscaralaniz** [bachya/Sifttter-Redux#11]
Hello!  I tried to install it on mi iMac, but I get this line:

```
OA-iMac:~ oscaralaniz$ srd init
error: uninitialized constant SifttterRedux::Configuration::Methadone
```

What's that? (Sorry to bother you again and thank you for your help.)

**Comment by bachya** [comment]
Hi Oscar! That is a constant that I no longer need and forgot to remove. 0.5.1 was just pushed and should fix it. Let me know?

**Comment by oscaralaniz** [comment]
Thank you!  Now it says:

```
OA-iMac:~ oscaralaniz$ srd init -s
error: Section does not exist: sifttter_redux
```

¿Am I doing something wrong? (Maybe I didn't update correctly, i used the sudo gem install sifttter-redux command, but it says I have 0.5.1.)

**Comment by bachya** [comment]
What does your config file look like?

On Tue, Mar 18, 2014 at 11:30 AM, oscaralaniz notifications@github.comwrote:

> Thank you! Now it says:
> 
> OA-iMac:~ oscaralaniz$ srd init -s
> error: Section does not exist: sifttter_redux
> 
> ¿Am I doing something wrong? (Maybe I didn't update correctly, i used the
> sudo gem install sifttter-redux command.)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bachya/Sifttter-Redux/issues/11#issuecomment-37962548
> .

## 

_Aaron Bachbachya1208@gmail.com bachya1208@gmail.com(720) 854-5753_

**Comment by oscaralaniz** [comment]
I did the 

```
cat ~/.sifttter_redux* | pbcopy
```

and it gave me:

```
# Logfile created on 2014-03-18 08:13:57 -0600 by logger.rb/36483
```

Do you think having Filevault active may be conflicting?  Because it is the only thing that changed from my MacBook and my iMac, and my MacBooks works perfect.  I am deactivating Filevault, just in case.

**Comment by bachya** [comment]
That looks like it created a log, but not a config file. Not sure about
Filevault; I've never used it before. Let me know what comes from
deactivating it.

On Tue, Mar 18, 2014 at 11:40 AM, oscaralaniz notifications@github.comwrote:

> I did the
> 
> cat ~/.sifttter_redux\* | pbcopy
> 
> and it gave me:
> 
> # Logfile created on 2014-03-18 08:13:57 -0600 by logger.rb/36483
> 
> Do you think having Filevault active may be conflicting? Because it is the
> only thing that changed from my MacBook and my iMac, and my MacBooks works
> perfect. I am deactivating Filevault, just in case.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bachya/Sifttter-Redux/issues/11#issuecomment-37963852
> .

## 

_Aaron Bachbachya1208@gmail.com bachya1208@gmail.com(720) 854-5753_

**Comment by oscaralaniz** [comment]
I think it will be deactivated in a couple hours.  In the meantime, I've got a question for you, but it is nothing serious.  When I install Sifttter-Redux, I have to "sudo" the command, I couldn't do it without it.  It tells me this:

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

Nothing serious, we all know how to "sudo" something.  Just wanted you to know.  Thank you for your help.  I really appreciate it.

**Comment by oscaralaniz** [comment]
I have deactivated Filevault, upgraded, and now it is working perfectly.  Thank you for your help.

**Comment by bachya** [comment]
Wonderful, Oscar!

On Thu, Mar 20, 2014 at 8:39 AM, oscaralaniz notifications@github.comwrote:

> I have deactivated Filevault, upgraded, and now it is working perfectly.
> Thank you for your help.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bachya/Sifttter-Redux/issues/11#issuecomment-38174421
> .

## 

_Aaron Bachbachya1208@gmail.com bachya1208@gmail.com(720) 854-5753_
