### ISSUE TITLE
configuration incomplete

### ISSUE THREAD

**Issue by miherrm** [bachya/Sifttter-Redux#12]
Hello Aaron,

I installed the new gem Version which fixed the Configuration::Methadone problem. Thanks for that!
I run "srd init" which downloads Dropbox-Uploader (which is then authorized) and aks for the necessary paths. After confirming the default paths (yes, I fitted my environment to the defaults) everything looks fine.
I run "srd exec" afterwards, to see if it works...nope. srd says, it needs to make some config changes. OK, lets go through the few steps. But when I try to run srd the next time the story starts right from the beginning...

``` ruby
# This version needs to make some config changes.
# Don't worry; when prompted, your current values for
# existing config options will be presented (so it'll
# be easier to fly through the upgrade).
# Press enter to continue:   
---> CONFIGURING DROPBOX UPLOADER...
# Location for Dropbox-Uploader [default: /Applications]: 
# Using pre-existing Dropbox Uploader at /Applications/Dropbox-Uploader...
---> COLLECTING PREFERENCES...
# Temporary path to download Sifttter files to  /tmp/sifttter
# Path to Sifttter files in Dropbox  /Apps/ifttt/sifttter
# Temporary path to download Day One files to  /tmp/dayone
# Path to Day One files in Dropbox  /Apps/Day\ One/Journal.dayone/entries
```

Looking at ~/.sifttter_redux reveals that the paths seem to be missing.
Following the results of 

`cat ~/.sifttter_redux | pbcopy`

``` ruby

---
sifttter_redux: {}
:db_uploader:
  :base_filepath: /Applications
  :dbu_filepath: /Applications/Dropbox-Uploader
  :exe_filepath: /Applications/Dropbox-Uploader/dropbox_uploader.sh
```

Even running "srd init" with sudo doesn't help.
Any idea?

**Comment by bachya** [comment]
Hi @miherrm! Sorry for the trouble. That config file is missing some info. Try this: with the latest gem, run `srd init -s`. Depending on the results, post back here with the content of `~/.sifttter_redux`. We'll get this resolved quickly!

**Comment by miherrm** [comment]
Hi,

after running `srd init -s` (btw, I had to run it with sudo rights, otherwise I get "permission denied" at the end),  `~/.sifttter_redux`looks like this - pretty much the same...

```
---
sifttter_redux: {}
:db_uploader:
  :base_filepath: /Applications
  :dbu_filepath: /Applications/Dropbox-Uploader
  :exe_filepath: /Applications/Dropbox-Uploader/dropbox_uploader.sh
```

**Comment by bachya** [comment]
FYI, you're getting that error because your `GEM_HOME` and/or `GEM_PATH` env variables aren't set (see here: https://stackoverflow.com/questions/2619695/gem-install-permission-problem).

I'm able to reproduce that configuration bug. Working on a fix now!

**Comment by bachya** [comment]
Thanks for your patience, @miherrm. I just pushed version 0.5.4, which should fix this issue. Please update your gem, run, and feel free to post a new issue if needed.

**Comment by miherrm** [comment]
Thanks for the fix - and the additional tip. I'll give it a try as soon as I'm back from work in the evening.

**Comment by miherrm** [comment]
Impatience vs. me - 1:0. :-) It's working like a charm, thank you!

**Comment by bachya** [comment]
Fantastic! Thanks so much for helping me find that bug!

**Comment by miherrm** [comment]
Your welcome. Thanks for maintaning this wonderful tool!
